filter:
    excluded_paths: [ 'vendor/*', 'tests/*', 'samples/*' ]

before_commands:
    - "composer install --prefer-source --dev"

tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_mess_detector: true
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
